/** Sync prices, context windows, and capabilities from models.dev into prices.yaml. Free, no key. */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { stringify, parse } from "yaml";
import { loadConfig, splitModel, PKG_ROOT } from "./config.js";
import type { Config, ModelMeta } from "./types.js";
import { join } from "node:path";

export const MODELS_DEV_URL = "https://models.dev/api.json";

interface ModelsDevModel {
  id: string; name?: string; release_date?: string; reasoning?: boolean; tool_call?: boolean;
  cost?: { input?: number; output?: number };
  limit?: { context?: number; output?: number };
  modalities?: { input?: string[]; output?: string[] };
}
type ModelsDev = Record<string, { id: string; models: Record<string, ModelsDevModel> }>;

export async function fetchModelsDev(fetchImpl: typeof fetch = fetch): Promise<ModelsDev> {
  const res = await fetchImpl(MODELS_DEV_URL);
  if (!res.ok) throw new Error(`models.dev returned HTTP ${res.status}`);
  return (await res.json()) as ModelsDev;
}

export function metaFromModelsDev(m: ModelsDevModel): ModelMeta {
  const caps: string[] = [];
  if (m.tool_call) caps.push("tools");
  if (m.reasoning) caps.push("reasoning");
  if (m.modalities?.input?.includes("image")) caps.push("vision");
  const meta: ModelMeta = {};
  if (m.cost && m.cost.input !== undefined && m.cost.output !== undefined) meta.price = { input: m.cost.input, output: m.cost.output };
  if (m.limit?.context) meta.context = m.limit.context;
  if (m.limit?.output) meta.max_output = m.limit.output;
  if (caps.length) meta.caps = caps;
  if (m.release_date) meta.release_date = m.release_date;
  return meta;
}

export interface SyncChange { model: string; field: string; from: unknown; to: unknown }
export interface SyncResult { changes: SyncChange[]; missing: string[]; local: string[]; written: boolean; path: string }

function isLocal(config: Config, providerName: string): boolean {
  const p = config.providers[providerName];
  return !p.api_key_env && /localhost|127\.0\.0\.1/.test(p.base_url ?? "");
}

/** Compare two metas field by field. Only fields present in `next` are compared. */
function diff(model: string, prev: ModelMeta | undefined, next: ModelMeta): SyncChange[] {
  const out: SyncChange[] = [];
  for (const field of ["price", "context", "max_output", "caps", "release_date"] as const) {
    const a = JSON.stringify(prev?.[field]), b = JSON.stringify(next[field]);
    if (b !== undefined && a !== b) out.push({ model, field, from: prev?.[field], to: next[field] });
  }
  return out;
}

export async function syncModels(opts: { configPath?: string; write: boolean; fetch?: typeof fetch } = { write: false }): Promise<SyncResult> {
  const config = loadConfig(opts.configPath);
  const pricesPath = join(PKG_ROOT, "prices.yaml");
  const existing: Record<string, ModelMeta> = existsSync(pricesPath) ? (parse(readFileSync(pricesPath, "utf8")) ?? {}) : {};
  const data = await fetchModelsDev(opts.fetch);
  const next: Record<string, ModelMeta> = { ...existing };
  const changes: SyncChange[] = [], missing: string[] = [], local: string[] = [];

  for (const id of Object.values(config.tiers).flat()) {
    const { provider, model } = splitModel(id);
    const pcfg = config.providers[provider];
    if (pcfg.models_dev === false) continue;
    if (isLocal(config, provider)) {
      local.push(id);
      const meta: ModelMeta = { ...existing[id], price: { input: 0, output: 0 } };
      changes.push(...diff(id, existing[id], meta)); next[id] = meta; continue;
    }
    const key = pcfg.models_dev ?? provider;
    const entry = data[key]?.models?.[model];
    if (!entry) { missing.push(id); continue; }
    const meta = { ...existing[id], ...metaFromModelsDev(entry) };
    changes.push(...diff(id, existing[id], meta));
    next[id] = meta;
  }

  const ordered = Object.fromEntries(Object.keys(next).sort().map((k) => [k, next[k]]));
  if (opts.write) {
    const header = `# Model metadata used by tiershift for context checks and cost estimates. USD per 1M tokens.\n# Generated by \`tiershift sync-models\` from ${MODELS_DEV_URL} on ${new Date().toISOString().slice(0, 10)}.\n# Override any value in tiershift.yaml under \`models:\`. Local models get price 0. Unknown models still route.\n\n`;
    writeFileSync(pricesPath, header + stringify(ordered));
  }
  return { changes, missing, local, written: opts.write, path: pricesPath };
}
